spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vmdb?useTimezone=true&serverTimezone=UTC
#        url: jdbc:mysql://localhost:3306/traveldb?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jackson:
    property-naming-strategy: SNAKE_CASE
    application:
      name: virtual-machine-manager

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update

server:
  port: 8090

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimeout: 5000
#        loggerLevel: basic
